#coleta de dados pessoais
nome = input('Digite o seu primeiro nome:')
print(nome,',Muito prazer em te conhecer!')
sobrenome = input('Agora digite o seu sobrenome:')
endereço = input('Digite o seu endeço, Rua, Av,Lavadouro,etc:')
número = input ('Digite o número da sua residência:')
complemento = input ('Digite algum complemento , local, apto, bloco, etc:')
cep = input ('Digite o número do seu cep:')
bairro = input ('Digite o nome do seu bairro:')
cidade = input ('Digite o nome da sua cidade:')
estado = input ('Digite o nome do seu estado:')
print ('As informações foram gravadas com sucesso.')